apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
spec:
  # Selector is used for both Deployment and ReplicaSet
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  # replicas is used to configure ReplicaSet
  replicas: 1
  # This part is a template to create Pods
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
